services:
  trainingtracker.api:
    container_name: trainingtracker.api
    build:
      context: ..
      dockerfile: TrainingTracker/Dockerfile
    ports:
      - "5027:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=trainingtracker.postgres;Port=5432;Database=training_tracker_db;Username=postgres;Password=postgres
    depends_on:
      trainingtracker.postgres:
        condition: service_healthy
    restart: unless-stopped    

  trainingtracker.postgres:
    image: postgres:16
    container_name: trainingtracker.postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: training_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - trainingtracker_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d training_tracker_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  trainingtracker_postgres_data: